[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
exclude = "migrations"

[tool.django-stubs]
django_settings_module = "repeatit.settings"
